version: "3"

services:
    fuzzy:
      build: .
      env_file:
        - .env
      container_name: fuzzy
      ports:
        - "5666:80"
      restart: always
      volumes:
        - "./processed:/usr/src/app/processed"
        - "./output_python:/usr/src/app/output_python"
